"""empty message

Revision ID: 5db6572ea39e
Revises: 
Create Date: 2023-06-28 11:39:51.974851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '5db6572ea39e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drink', schema=None) as batch_op:
        batch_op.alter_column('alcohol_porcentage',
               existing_type=mssql.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('ingridient', schema=None) as batch_op:
        batch_op.alter_column('alcohol_porcentage',
               existing_type=mssql.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=mssql.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.Float(precision=2),
               type_=mssql.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ingridient', schema=None) as batch_op:
        batch_op.alter_column('alcohol_porcentage',
               existing_type=sa.Float(precision=2),
               type_=mssql.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('drink', schema=None) as batch_op:
        batch_op.alter_column('alcohol_porcentage',
               existing_type=sa.Float(precision=2),
               type_=mssql.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
